name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-version: ['8.4']

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: mbstring, xml, ctype, iconv, intl

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress

            - name: Run validation
              run: composer validate --strict

            - name: Run PHP CS Fixer
              run: composer fix

            - name: Run PHPStan
              run: composer phpstan

            - name: Run tests
              run: composer cover
